export const RESPONSE_LOG_IN_SUCCESS = 'RESPONSE_LOG_IN_SUCCESS';
export const RESPONSE_LOG_IN_NOT_FOUND = 'RESPONSE_LOG_IN_NOT_FOUND';
export const RESPONSE_LOG_IN_EMAIL_NOT_VERIFIED = 'RESPONSE_LOG_IN_EMAIL_NOT_VERIFIED';
export const RESPONSE_LOG_IN_FAILURE = 'RESPONSE_LOG_IN_FAILURE';

export const RESPONSE_REGISTER_CONFLICT = 'RESPONSE_REGISTER_CONFLICT';
export const RESPONSE_REGISTER_FAILURE = 'RESPONSE_REGISTER_FAILURE';

export const RESPONSE_VERIFY_SUCCESS = 'RESPONSE_VERIFY_SUCCESS';
export const RESPONSE_VERIFY_INVALID_VERIFICATION_TOKEN = 'RESPONSE_VERIFY_INVALID_VERIFICATION_TOKEN';
export const RESPONSE_VERIFY_FAILURE = 'RESPONSE_VERIFY_FAILURE';

export const RESPONSE_SEND_PASSWORD_RESET_SUCCESS = 'RESPONSE_SEND_PASSWORD_RESET_SUCCESS';
export const RESPONSE_SEND_PASSWORD_NOT_FOUND = 'RESPONSE_SEND_PASSWORD_NOT_FOUND';
export const RESPONSE_SEND_PASSWORD_RESET_FAILURE = 'RESPONSE_SEND_PASSWORD_RESET_FAILURE';

export const RESPONSE_SEND_VERIFICATION_EMAIL_SUCCESS = 'RESPONSE_SEND_VERIFICATION_EMAIL_SUCCESS';
export const RESPONSE_SEND_VERIFICATION_EMAIL_NOT_FOUND = 'RESPONSE_SEND_VERIFICATION_EMAIL_NOT_FOUND';
export const RESPONSE_SEND_VERIFICATION_EMAIL_FAILURE = 'RESPONSE_SEND_VERIFICATION_EMAIL_FAILURE';



export const ACCOUNT_TYPE_INTERNAL = 'ACCOUNT_TYPE_INTERNAL';
export const ACCOUNT_TYPE_GOOGLE = 'ACCOUNT_TYPE_GOOGLE';


export const NOT_FETCHING = 'NOT_FETCHING';
export const IS_FETCHING = 'IS_FETCHING';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_FAILED_NOT_FOUND = 'FETCH_FAILED_NOT_FOUND';
