export const RESPONSE_LOG_IN_SUCCESS = 'RESPONSE_LOG_IN_SUCCESS';
export const RESPONSE_LOG_IN_NOT_FOUND = 'RESPONSE_LOG_IN_NOT_FOUND';
export const RESPONSE_LOG_IN_EMAIL_NOT_VERIFIED = 'RESPONSE_LOG_IN_EMAIL_NOT_VERIFIED';
export const RESPONSE_LOG_IN_FAILURE = 'RESPONSE_LOG_IN_FAILURE';

export const RESPONSE_REGISTER_CONFLICT = 'RESPONSE_REGISTER_CONFLICT';
export const RESPONSE_REGISTER_FAILURE = 'RESPONSE_REGISTER_FAILURE';

export const RESPONSE_VERIFY_SUCCESS = 'RESPONSE_VERIFY_SUCCESS';
export const RESPONSE_VERIFY_INVALID_VERIFICATION_TOKEN = 'RESPONSE_VERIFY_INVALID_VERIFICATION_TOKEN';
export const RESPONSE_VERIFY_FAILURE = 'RESPONSE_VERIFY_FAILURE';

export const RESPONSE_SEND_PASSWORD_RESET_SUCCESS = 'RESPONSE_SEND_PASSWORD_RESET_SUCCESS';
export const RESPONSE_SEND_PASSWORD_NOT_FOUND = 'RESPONSE_SEND_PASSWORD_NOT_FOUND';
export const RESPONSE_SEND_PASSWORD_RESET_FAILURE = 'RESPONSE_SEND_PASSWORD_RESET_FAILURE';

export const RESPONSE_SEND_VERIFICATION_EMAIL_SUCCESS = 'RESPONSE_SEND_VERIFICATION_EMAIL_SUCCESS';
export const RESPONSE_SEND_VERIFICATION_EMAIL_NOT_FOUND = 'RESPONSE_SEND_VERIFICATION_EMAIL_NOT_FOUND';
export const RESPONSE_SEND_VERIFICATION_EMAIL_FAILURE = 'RESPONSE_SEND_VERIFICATION_EMAIL_FAILURE';

export const RESPONSE_PASSWORD_RESET_SUCCESS = 'RESPONSE_PASSWORD_RESET_SUCCESS';
export const RESPONSE_PASSWORD_USER_NOT_FOUND = 'RESPONSE_PASSWORD_USER_NOT_FOUND';
export const RESPONSE_PASSWORD_RESET_INVALID_PASSWORD = 'RESPONSE_PASSWORD_RESET_INVALID_PASSWORD';
export const RESPONSE_PASSWORD_RESET_FAILURE = 'RESPONSE_SEND_PASSWORD_RESET_FAILURE';
export const RESPONSE_PASSWORD_INVALID_TOKEN = 'RESPONSE_PASSWORD_INVALID_TOKEN';

export const RESPONSE_IS_PASSWORD_RESET_TOKEN_VALID_YES = 'RESPONSE_IS_PASSWORD_RESET_TOKEN_VALID_YES';
export const RESPONSE_IS_PASSWORD_RESET_TOKEN_VALIDL_NO = 'RESPONSE_IS_PASSWORD_RESET_TOKEN_VALIDL_NO';
export const RESPONSE_IS_PASSWORD_RESET_TOKEN_VALID_FAILURE = 'RESPONSE_IS_PASSWORD_RESET_TOKEN_VALID_FAILURE';

export const ACCOUNT_TYPE_INTERNAL = 'ACCOUNT_TYPE_INTERNAL';
export const ACCOUNT_TYPE_GOOGLE = 'ACCOUNT_TYPE_GOOGLE';

export const NOT_FETCHING = 'NOT_FETCHING';
export const IS_FETCHING = 'IS_FETCHING';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_FAILED_NOT_FOUND = 'FETCH_FAILED_NOT_FOUND';

export const NOT_VALIDATING = 'NOT_VALIDATING';
export const IS_VALIDATING = 'IS_VALIDATING';
export const VALIDATION_NO_CONFLICT = 'VALIDATION_NO_CONFLICT';
export const VALIDATION_FAILED = 'VALIDATION_FAILED';
export const VALIDATION_CONFLICT = 'VALIDATION_CONFLICT';
export const VALIDATION_INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT';

export const NOT_PROCESSING = 'NOT_PROCESSING';
export const IS_PROCESSING = 'IS_PROCESSING';
export const PROCESS_SUCCEDEED = 'PROCESS_SUCCEDEED';
export const PROCESS_FAILED = 'PROCESS_FAILED';

export const MESSAGE_SUCCESS = 'message-success';
export const MESSAGE_FAILURE = 'message-failure';
export const MESSAGE_NONE = 'message-none';
