export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

export const SELECT_MODEL_PORTFOLIO = 'SELECT_MODEL_PORTFOLIO';
export const CREATE_NEW_PORTFOLIO = 'CREATE_NEW_PORTFOLIO';
export const ADD_SECURITY = 'ADD_SECURITY';
export const REMOVE_SECURITY = 'REMOVE_SECURITY';

export const SECURITY_TEXT_FIELD_CHANGE = 'SECURITY_TEXT_FIELD_CHANGE';
export const SECURITY_TEXT_FIELD_VALID = 'SECURITY_TEXT_FIELD_VALID';
export const SECURITY_TEXT_FIELD_ERROR = 'SECURITY_TEXT_FIELD_ERROR';

export const INVESTMENT_AMOUNT_TEXT_FIELD_CHANGE = 'INVESTMENT_AMOUNT_TEXT_FIELD_CHANGE';
export const INVESTMENT_AMOUNT_TEXT_FIELD_VALID = 'INVESTMENT_AMOUNT_TEXT_FIELD_VALID';
export const INVESTMENT_AMOUNT_TEXT_FIELD_ERROR = 'INVESTMENT_AMOUNT_TEXT_FIELD_ERROR';

export const GENERATE_STEPS = 'GENERATE_STEPS';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
