export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CHANGE_TAB = 'CHANGE_TAB';

export const MODEL_PORTFOLIOS_AUTO_COMPLETE_SEARCH_TEXT_CHANGE = 'MODEL_PORTFOLIOS_AUTO_COMPLETE_SEARCH_TEXT_CHANGE';

export const SELECT_MODEL_PORTFOLIO = 'SELECT_MODEL_PORTFOLIO';
export const CREATE_NEW_PORTFOLIO = 'CREATE_NEW_PORTFOLIO';
export const ADD_SECURITY = 'ADD_SECURITY';
export const REMOVE_SECURITY = 'REMOVE_SECURITY';

export const MODEL_PORTFOLIO_NAME_TEXT_FIELD_CHANGE = 'MODEL_PORTFOLIO_NAME_TEXT_FIELD_CHANGE';

export const SECURITY_TEXT_FIELD_CHANGE = 'SECURITY_TEXT_FIELD_CHANGE';
export const SECURITY_TEXT_FIELD_VALID = 'SECURITY_TEXT_FIELD_VALID';
export const SECURITY_TEXT_FIELD_ERROR = 'SECURITY_TEXT_FIELD_ERROR';

export const INVESTMENT_AMOUNT_TEXT_FIELD_CHANGE = 'INVESTMENT_AMOUNT_TEXT_FIELD_CHANGE';
export const INVESTMENT_AMOUNT_TEXT_FIELD_VALID = 'INVESTMENT_AMOUNT_TEXT_FIELD_VALID';
export const INVESTMENT_AMOUNT_TEXT_FIELD_ERROR = 'INVESTMENT_AMOUNT_TEXT_FIELD_ERROR';

export const GENERATE_STEPS = 'GENERATE_STEPS';

export const CREATE_MODEL_PORTFOLIO_REQUEST = 'CREATE_MODEL_PORTFOLIO_REQUEST';
export const CREATE_MODEL_PORTFOLIO_FAILURE = 'CREATE_MODEL_PORTFOLIO_FAILURE';
export const CREATE_MODEL_PORTFOLIO_SUCCESS = 'CREATE_MODEL_PORTFOLIO_SUCCESS';
export const CREATE_MODEL_PORTFOLIO_DUPLICATE = 'CREATE_MODEL_PORTFOLIO_DUPLICATE';

export const SAVE_MODEL_PORTFOLIO_REQUEST = 'SAVE_MODEL_PORTFOLIO_REQUEST';
export const SAVE_MODEL_PORTFOLIO_FAILURE = 'SAVE_MODEL_PORTFOLIO_FAILURE';
export const SAVE_MODEL_PORTFOLIO_SUCCESS = 'SAVE_MODEL_PORTFOLIO_SUCCESS';
export const SAVE_MODEL_PORTFOLIO_DUPLICATE = 'SAVE_MODEL_PORTFOLIO_DUPLICATE';

export const DELETE_MODEL_PORTFOLIO_REQUEST = 'DELETE_MODEL_PORTFOLIO_REQUEST';
export const DELETE_MODEL_PORTFOLIO_FAILURE = 'DELETE_MODEL_PORTFOLIO_FAILURE';
export const DELETE_MODEL_PORTFOLIO_SUCCESS = 'DELETE_MODEL_PORTFOLIO_SUCCESS';

export const SET_PRICE_TO_FETCHING = 'SET_PRICE_TO_FETCHING';
export const SET_PRICE_TO_NOT_FETCHING = 'SET_PRICE_TO_NOT_FETCHING';
export const SET_PRICE_FROM_FETCH = 'SET_PRICE_FROM_FETCH';
export const SET_PRICE_TO_FETCH_FAILED = 'SET_PRICE_TO_FETCH_FAILED';

export const EMAIL_TEXT_FIELD_CHANGE = 'EMAIL_TEXT_FIELD_CHANGE';
export const EMAIL_TEXT_FIELD_VALIDATE = 'EMAIL_TEXT_FIELD_VALIDATE';
export const EMAIL_TEXT_FIELD_SET_VALIDATION_TIMEOUT = 'EMAIL_TEXT_FIELD_SET_VALIDATION_TIMEOUT';
export const BEGIN_EMAIL_ADDRESS_VALIDATION = 'BEGIN_EMAIL_ADDRESS_VALIDATION';
export const FINISH_EMAIL_ADDRESS_VALIDATION = 'FINISH_EMAIL_ADDRESS_VALIDATION';
export const PASSWORD_TEXT_FIELD_CHANGE = 'PASSWORD_TEXT_FIELD_CHANGE';
export const PASSWORD_CONFIRMATION_TEXT_FIELD_CHANGE = 'PASSWORD_CONFIRMATION_TEXT_FIELD_CHANGE';
export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_FINISH = 'REGISTRATION_FINISH';

export const SET_SCROLLED_TO_BOTTOM = 'SET_SCROLLED_TO_BOTTOM';

export const CHANGE_AUTHENTICATION_MODE = 'CHANGE_AUTHENTICATION_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const LOGIN_HASTY_USER = 'LOGIN_HASTY_USER';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const SIGNUP_HASTY_USER = 'SIGNUP_HASTY_USER';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const SEND_VERIFICATION_EMAIL_USER = 'SEND_VERIFICATION_EMAIL_USER';
export const SEND_VERIFICATION_EMAIL_SUCCESS_USER = 'SEND_VERIFICATION_EMAIL_SUCCESS_USER';
export const SEND_VERIFICATION_EMAIL_ERROR_USER = 'SEND_VERIFICATION_EMAIL_ERROR_USER';

export const VERIFY_USER = 'VERIFY_USER';
export const VERIFY_SUCCESS_USER = 'VERIFY_SUCCESS_USER';
export const VERIFY_ERROR_USER = 'VERIFY_ERROR_USER';

export const PASSWORD_RESET_USER = 'PASSWORD_RESET_USER';
export const PASSWORD_RESET_SUCCESS_USER = 'PASSWORD_RESET_SUCCESS_USER';
export const PASSWORD_RESET_ERROR_USER = 'PASSWORD_RESET_ERROR_USER';
